### ISSUE TITLE
No documented default admin credentials.

### ISSUE THREAD

**Issue by Leopere** [docker-taiga/taiga#13]
I've gotten a tryout instance up and running but there doesn't appear to be any documentation on how to create initial users or what the default credentials are despite finding `admin` and `123123` for the password documented randomly.

**Comment by w1ck3dg0ph3r** [comment]
Added the default taiga user/password to README, thanks.

**Comment by Leopere** [comment]
I feel like my problem might've been something else but thanks for the documentation.

**Comment by kokoye2007** [comment]
admin & 123123 is not working

**Comment by Leopere** [comment]
@kokoye2007 to be honest my issue was that I was putting this thing behind a Traefik reverse proxy and for the most part that never causes an issue but theres something janky about how Taiga operates so its been since 2014 and I still can't use this technology because self hosting is too much of a pain.

**Comment by kokoye2007** [comment]
> @kokoye2007 to be honest my issue was that I was putting this thing behind a Traefik reverse proxy and for the most part that never causes an issue but theres something janky about how Taiga operates so its been since 2014 and I still can't use this technology because self hosting is too much of a pain.

sorry 
its depend on proxy services (host)
i try change host and test its working
also ssl, bash autocomplete / auto config is not working
but you can manual config in conf/proxy/  with start.sh rule
its working.

**Comment by Leopere** [comment]
Do you have an example on what kind of changes you're suggesting @kokoye2007? Perhaps paste the change in here.

**Comment by kokoye2007** [comment]
# 1 
## Just work with admin and 123123
* edit variables.env 
```
TAIGA_HOST=taiga.lan
```
to your real host
```
TAIGA_HOST=taiga.mydomain.com
```
go to 3
# 2
## if you want to change https ? ## 
* create fullchain.pem and privkey.pem 
 * i am work with https://www.linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/
 * make cert folder, copy fullchain.pem and privkey.pem into cert foler
## edit variables.env 
 * http to https
 * ENABLE_SSL='no' to ENABLE_SSL='yes'
 * change comment # CERT_NAME=fullchain.pem # CERT_KEY=privkey.pem

```
TAIGA_SCHEME=https
..
..
ENABLE_SSL='yes'
CERT_NAME=fullchain.pem
CERT_KEY=privkey.pem
```
edit docker-compose.yml
```
      #- ./cert:/taiga-cert
```
to 
```
      - ./cert:/taiga-cert
```
# 3
## Clean and Try
```
docker-compose stop
docker-compose down
docker-compose up
```
check log and try with your real host name.

# 4
## still error with HTTPS
check 
- front https://github.com/docker-taiga/front
- proxy https://github.com/docker-taiga/proxy
example check [start.sh](https://github.com/docker-taiga/proxy/blob/latest/start.sh) and nginx.conf or  [nginx_ssl.conf](https://github.com/docker-taiga/proxy/blob/latest/nginx_ssl.conf)
replease manual hostname and copy paste in conf/front conf/proxy 
 and retry Number 3

# 5 
## Its perfect ? daemon mode
run in daemon mode
```
docker-compose -f your-compse/path/and/file.yaml
```
## make systemd service file
[Example](https://github.com/MiGoller/dc-systemd-template)

**Comment by Leopere** [comment]
@kokoye2007 my issue is that I am using a reverse proxy called Traefik to proxy about 20 other web-apps on this host through 443/80 with TLS upgrading and lets encrypt maintainance automatically handled at the border.  I don't really want Taiga handling the encryption if at all possible and for some reason the second I plunk this sucker behind Traefik Taiga's default credentials fail.
