### ISSUE TITLE
Add versions tags to docker hub images

### ISSUE THREAD

**Issue by 4n70w4** [docker-taiga/taiga#16]
Hi! Good practice add tags with versions for images.

You images:
![image](https://user-images.githubusercontent.com/38257723/53110844-f5416100-354c-11e9-89c8-0150d4eaa8b4.png)
![image](https://user-images.githubusercontent.com/38257723/53110871-fbcfd880-354c-11e9-8749-8498e0855bba.png)

Good practice:

![image](https://user-images.githubusercontent.com/38257723/53111184-af38cd00-354d-11e9-8ff1-1bb570f477c8.png)
![image](https://user-images.githubusercontent.com/38257723/53111200-b6f87180-354d-11e9-9212-2f3f1efe7242.png)

**Comment by w1ck3dg0ph3r** [comment]
Hi! Yes, absolutely. I'll try to get to updating images to pull specific tags rather than stable branch and docker-compose to explicitly state the version soon when I have the chance.

**Comment by w1ck3dg0ph3r** [comment]
Closed (kinda) in 7aae4860cb17f2d0c9ab8d9edad60ad35100d6c1
