### ISSUE TITLE
Pin postgres to a major version tag?

### ISSUE THREAD

**Issue by themightychris** [docker-taiga/taiga#17]
I just restarted my setup based on this docker-compose config and got surprised by my instance not coming up now because postgres got a major version bump. I didn't find any guidance on ideal postgres version other than >= 9.4

Would it make sense to specify a major version tag for postgres in docker-compose?

**Comment by w1ck3dg0ph3r** [comment]
> Would it make sense to specify a major version tag for postgres in docker-compose?

I do exactly that, for when I set up taiga for my team, the latest major postgres version was 9, and I didn't get around to migrate db to the new version yet.

But I'm not sure whether it would be better to pin postgres to the latest major version and document db migration from 9 to 10, or to stick with the version 9?

**Comment by themightychris** [comment]
FWIW, my install started on 10 and then got broken by 11

Maybe 11 would be the best choice, because that's what people installing fresh now would get anyway. We can at least start leaving new installers in control of when postgres jumps next

**Comment by w1ck3dg0ph3r** [comment]
Pinned to 11 in 7f217fee88128f304c2138603dd3703eb163df99
