### ISSUE TITLE
The docker-compose up stuck at Trying import local.py

### ISSUE THREAD

**Issue by chartchai** [docker-taiga/taiga#19]
I have tried to use docker-compose to run the Taica, I use the docker-compose file and the variable.env as given in the Github. However, I have changed the TAIGA_HOST value to my URL.
and when I start the containers using the docker-compose up. I always stuck to this error. I have tried on my computer, and my AWS EC2 and it returns the same result.
![image](https://user-images.githubusercontent.com/9063299/57793724-3623cd00-776c-11e9-8380-c60728a54571.png)

**Comment by Electron-libre** [comment]
I had the same issue.
I stoped the caintainers and up again, as a workaround.

**Comment by Electron-libre** [comment]
Indeed the container is not stuck.
It is just the last log entry.
But I had to run the  `python manage.py loaddata initial_user` manualy to populate users

**Comment by w1ck3dg0ph3r** [comment]
Can you confirm, please, that taiga is not working at this point? I have the same output from taiga-back container and everything is working smoothly, including creating default admin user. IIRC, "Trying to import..." is not an error, there's just no "finished" message.

**Comment by chartchai** [comment]
dear @w1ck3dg0ph3r  I have tried again, and restart the container as @Electron-libre suggest, and I work.
Could not understand what happened before.
Thank you for your helps

**Comment by w1ck3dg0ph3r** [comment]
I'm glad it works now, though the message itself is not an error, as you can see here: https://github.com/taigaio/taiga-back/blob/master/settings/__init__.py#L25, so closing for now.
