### ISSUE TITLE
Will this ever finish?

### ISSUE THREAD

**Issue by Leopere** [docker-taiga/taiga#20]
![Screenshot](https://i.imgur.com/hnfX630.png)

**Comment by Leopere** [comment]
Looks as though leaving it alone all day made no difference.

**Comment by w1ck3dg0ph3r** [comment]
This is not an indication of error as far as I can tell (https://github.com/taigaio/taiga-back/blob/master/settings/__init__.py#L25), there is just no 'finished' message.

**Comment by Leopere** [comment]
Very strange, well I’ll check back in a few months again I guess I want to
run Taiga but I want it in docker behind my Traefik reverse proxy or I have
no use for it. Your stuff here has gotten me far closer than anyone else so
far.

**Comment by wub1990** [comment]
I also have the problem. Has it finished with you?

**Comment by Leopere** [comment]
@wub1990 No I left it going all day and nothing seemed to be changing however my CPU was pinned for ages over it so idk.

**Comment by w1ck3dg0ph3r** [comment]
Could the CPU usage be caused by improper Traefik config, e.g. it retrying requests over and over?
I have exactly the same output from taiga-back:
```
taiga-back | Copying '/srv/taiga/back/taiga/base/static/img/emojis/open_file_folder.png'
taiga-back | Copying '/srv/taiga/back/taiga/base/static/img/emojis/battery.png'
taiga-back | Copying '/srv/taiga/back/taiga/base/static/img/emojis/inbox_tray.png'
taiga-back | Copying '/srv/taiga/back/taiga/base/static/img/emojis/santa.png'
taiga-back | Copying '/srv/taiga/back/taiga/users/static/img/user-noimage.png'
taiga-back | 
taiga-back | 939 static files copied to '/srv/taiga/back/static'.
taiga-back | Trying import local.py settings...
taiga-back | Trying import local.py settings...
```
But the CPU is idle, unless I actually use taiga, and the container works as expected:
![Screenshot_20190927_102027](https://user-images.githubusercontent.com/10450851/65750432-0ff63c80-e111-11e9-9d48-a1e0ad648528.png)
