### ISSUE TITLE
Update containers for Taiga 4.2.12

### ISSUE THREAD

**Issue by vlude** [docker-taiga/taiga#22]
Hi,
The most current version of your container seem te be compiled 7 months ago. Any change you could update them for the newest taiga versions?

Thanks for effort. Greatly appreciating your work.

**Comment by w1ck3dg0ph3r** [comment]
Hi!
Thanks, I'll try to get to #16 and this as soon as possible. But right now I'm a little bit short on spare time, so any pull requests are welcome.

**Comment by vlude** [comment]
Hi,
looking at your docker files, it does not seems that you are cloning a specific version of the taiga repositories. A rebuild of the containers itself might be enough.

**Comment by w1ck3dg0ph3r** [comment]
The dockertaiga/back and dockertaiga/front images now have tags and 4.2.14 is the latest. Not sure if 5.0 is ready yet, as no announcement has been made by taiga team.

**Comment by vlude** [comment]
Thanks for the effort
