### ISSUE TITLE
FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership

### ISSUE THREAD

**Issue by 4n70w4** [docker-taiga/taiga#3]
`git clone https://github.com/docker-taiga/taiga.git`

or

`git clone --depth=1 -b latest https://github.com/docker-taiga/taiga.git`

`cd .\taiga\`

`docker-compose up`

```
taiga-db  | creating configuration files ... ok
taiga-db  | 2018-12-04 06:56:29.262 UTC [47] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
taiga-db  | 2018-12-04 06:56:29.262 UTC [47] HINT:  The server must be started by the user that owns the data directory.
taiga-db  | child process exited with exit code 1
```

`docker-compose run db ls -la /var/lib/postgresql/data/`

```
total 8
drwxrwxrwx    1 1000     50            4096 Dec  4 07:00 .
drwxr-xr-x    3 postgres postgres      4096 Nov  9 23:15 ..
```

**Comment by 4n70w4** [comment]
Okay. https://github.com/docker/for-win/issues/445

**Comment by w1ck3dg0ph3r** [comment]
Is this reproducible only on windows? Can we change compose file to mitigate this?

**Comment by 4n70w4** [comment]
@w1ck3dg0ph3r 
I tried only in windows, well, I can do PR a bit later.
