### ISSUE TITLE
Email support?

### ISSUE THREAD

**Issue by adechassey** [docker-taiga/taiga#31]
Hi,
Are there some env variables to set so we can use emails?
I did not find how to get emails to work.
Thx a lot for the great work!

**Comment by w1ck3dg0ph3r** [comment]
Hi! SMTP settings are available in config.py (`./conf/back/config.py` if you use the default docker-compose.yml volumes): https://github.com/docker-taiga/back/blob/a86fa380894aab80d3d602582f7150c0681a32a7/config.py#L27
The idea was that variables.env should contain infrastructure-specific variables only, with application configuration being mapped from a volume.

**Comment by w1ck3dg0ph3r** [comment]
Note, that you need to restart taiga-back container after modifying the configuration

**Comment by hellfirehd** [comment]
My Taiga instance can send email notifications but only seems to do so for user account related functions (invite, password, etc).  Is there a setting in the config.py that will make Taiga send emails for project related events as well (e.g. new issue, comment, etc.)?

**Comment by w1ck3dg0ph3r** [comment]
@hellfirehd It seems if you set `CHANGE_NOTIFICATIONS_MIN_INTERVAL` to something greater than zero, you have to execute `python3 manage.py send_notifications` periodically:
https://github.com/taigaio/taiga-back/issues/1251

That was not in taiga.io docs, so I missed that. Will add the cronjob to the image in the future.

**Comment by w1ck3dg0ph3r** [comment]
@hellfirehd  Should be fixed in https://github.com/docker-taiga/back/commit/684f9070108b3319dcfc7ee2b6959169165e8e79

**Comment by LakshyAAAgrawal** [comment]
Hey, I would suggest adding this to the readme. Shall I create a pull request?
