### ISSUE TITLE
Not working other port than 80

### ISSUE THREAD

**Issue by gusarg81** [docker-taiga/taiga#35]
Hi, when I try to set another port than 80 (ex, 880) in docker-compose.yml, then when I open http://ip:880 just gives me an error (which I can't find what is going on). 

It does work with default 80 port (didnt tested SSL with an alternative 443 port).

Any ideas?

Thanks.

**Comment by gusarg81** [comment]
Ok, fixed this by setting in all related files in /conf/ to the configured alternative port. Shouldn't this be done by the docker settings?

**Comment by w1ck3dg0ph3r** [comment]
Hi! Sorry for late reply.

> Shouldn't this be done by the docker settings?

Well, there were no use cases for this atm.

Added TAIGA_PORT config variable in 9003c90f4587cf1a0de6f5818e0f01003038d031.
