### ISSUE TITLE
Can't upload >1MB file

### ISSUE THREAD

**Issue by PanBartosz** [docker-taiga/taiga#4]
If I try to upload file that is over 1MB (under 1MB it works) I get nginx error: `client intended to send too large body`.
To solve this issue I modified my nginx.conf to include this in a `server` section:
```
	client_max_body_size 100m;
	client_body_buffer_size 50m;
```
The effect of such modification is that nginx no longer responds with error but file upload for files >1MB is still not working. Is there anything I can do about it? In `docker-compose logs` there are no hints (no error messages).

**Comment by w1ck3dg0ph3r** [comment]
Hi! In which container did you change max body size? I believe client_max_body_size should be raised in taiga-back as well as on reverse proxy.

**Comment by w1ck3dg0ph3r** [comment]
Closing for now due to inactivity, feel free to reopen.

**Comment by dschick** [comment]
Hi, I am actually struggling with this as well.
I added this into my `conf/proxy/nginx.conf`
```
server {
        server_name xxx;
        listen 80;
        client_max_body_size 100M;
        client_body_buffer_size 50M;
```
where should one raise this for the `taiga-back`?

**Comment by dschick** [comment]
I actually solved the issue myself by adjusting the `client_max_body_size` within the `nginx` docker container which I use for providing multiple virtual hosts on my machine.
