### ISSUE TITLE
Can't view Issues, but can create them( Error: Something happened and our Oompa Loompas are working on it.)

### ISSUE THREAD

**Issue by ranasats** [docker-taiga/taiga#40]
Hi,

I setup my taiga instance and made a few test users. On one of my users, I created a sample scrum, and created a few issues. The issues create fine, but whenever I click on them I get the error: Something happened and our Oompa Loompas are working on it.

What additional error logs would you need to help troubleshoot this issue? Happy to provide additional context just let me know what!

Thanks!

**Comment by w1ck3dg0ph3r** [comment]
Hi! Can't reproduce this, maybe logs from taiga-back container would help figuring out what's up.
