### ISSUE TITLE
Celery worker is missing

### ISSUE THREAD

**Issue by yomguy** [docker-taiga/taiga#44]
Hi,

Thanks a lot for the setup!

As the composition is defined, there is no celery worker to take the asynchronous tasks sent by the `back` container through the `redis` one. As a result, for example, the timelines of the projects are not updated automatically.

If we agree on this fact, I could provide a PR.

**Comment by w1ck3dg0ph3r** [comment]
Hi! 
Celery worker should be started along with backend since https://github.com/docker-taiga/back/commit/06125618f16a9f831c27f82a7666f179983297d5: 
https://github.com/docker-taiga/back/blob/97df7710df01d24b199208e2cca1579cef233d5a/start.sh#L76

**Comment by yomguy** [comment]
Great @w1ck3dg0ph3r it indeed works!
