### ISSUE TITLE
Upgrade to v6

### ISSUE THREAD

**Issue by sim6** [docker-taiga/taiga#50]
Firstly, thanks for your work.

Please could you upgrade to v6.

Thanks.

**Comment by w1ck3dg0ph3r** [comment]
Thanks, will do, didn't have the time to follow upstream)

**Comment by sim6** [comment]
Thanks for the fast reply.

**Comment by w1ck3dg0ph3r** [comment]
6.2.0 is the latest

**Comment by sim6** [comment]
Thanks
